# -*- coding: utf-8 -*-
"""Bundle the card JSONs into viewer/cards_data.js so the viewer works from file://.

Browsers block fetch() of local files (CORS), so a double-clicked index.html cannot read
../cards/*.json. A <script> tag has no such restriction — this script embeds every card
as window.CARD_DATA. The viewer still PREFERS a live fetch (so the GitHub Pages copy
always shows the current cards) and falls back to this bundle only when fetch fails.

Rerun after regenerating cards:  python viewer/build_data.py
"""
import glob
import json
import os
import sys

sys.stdout.reconfigure(encoding="utf-8")
HERE = os.path.dirname(os.path.abspath(__file__))
CARDS = os.path.join(HERE, "..", "cards")

data = {}
for fp in sorted(glob.glob(os.path.join(CARDS, "*_evidence_card.json"))):
    j = json.load(open(fp, encoding="utf-8"))
    data[os.path.basename(fp)] = j

out = os.path.join(HERE, "cards_data.js")
with open(out, "w", encoding="utf-8", newline="\n") as f:
    f.write("// Generated by viewer/build_data.py — do not edit by hand.\n")
    f.write("window.CARD_DATA = ")
    json.dump(data, f, ensure_ascii=False, separators=(",", ":"))
    f.write(";\n")
print(f"bundled {len(data)} cards -> {out} ({os.path.getsize(out)//1024} KB)")
